name = "SpectralDensities"
uuid = "6f27643f-8ff7-45b5-8e20-15c87f132b4c"
authors = ["Federico Cerisola <federico@cerisola.net"]
version = "1.0.0-DEV"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
QuadGK = "2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
